'use strict';
const assert=require('node:assert/strict');
const {chooseRoute}=require('../src/execution/capability-router');
const locked={interactive:false,locked:true};
const unlocked={interactive:true,locked:false};
const c={directFilesystem:true,directProcessSessions:true,browserCdp:true,uia:true,elevated:false};
let checked=0;const yes=(x,expect)=>{for(const [k,v] of Object.entries(expect))assert.deepEqual(x[k],v,k);checked++};
yes(chooseRoute({kind:'file_read',session:locked,agent:c}),{route:'background.filesystem',ready:true,worksWhileLocked:true});
yes(chooseRoute({kind:'file_write',session:locked,agent:c}),{route:'background.filesystem',ready:true,worksWhileLocked:true});
yes(chooseRoute({kind:'process_run',session:locked,agent:c}),{route:'background.process',ready:true,worksWhileLocked:true});
yes(chooseRoute({kind:'browser',session:locked,agent:c,browser:{running:true}}),{route:'browser.cdp',ready:true,worksWhileLocked:true});
yes(chooseRoute({kind:'browser',session:locked,agent:c,browser:{running:false}}),{route:'browser_not_ready',ready:false});
yes(chooseRoute({kind:'browser',session:locked,agent:c,browser:{running:false},allowBrowserStart:true}),{route:'browser.cdp_start',ready:true});
yes(chooseRoute({kind:'desktop',session:locked,agent:c}),{route:'waiting_for_interactive_session',ready:false,reason:'WINDOWS_SECURE_DESKTOP'});
yes(chooseRoute({kind:'desktop',session:{interactive:false,locked:false},agent:c}),{route:'waiting_for_interactive_session',ready:false,reason:'NO_INTERACTIVE_SESSION'});
yes(chooseRoute({kind:'desktop',session:unlocked,agent:c}),{route:'windows.uia_guarded',ready:true});
yes(chooseRoute({kind:'desktop',session:locked,agent:c,alternate:{kind:'file_read'}}),{route:'background.filesystem',ready:true,originalKind:'desktop'});
yes(chooseRoute({kind:'desktop',session:locked,agent:c,alternate:{kind:'desktop'}}),{route:'waiting_for_interactive_session',ready:false});
yes(chooseRoute({kind:'file_read',session:locked,agent:c,requiresAdmin:true}),{route:'authorized_admin_provisioning',ready:false,reason:'ELEVATION_NOT_PROVISIONED'});
yes(chooseRoute({kind:'process_run',session:locked,agent:{...c,elevated:true},requiresAdmin:true}),{route:'background.process',ready:true,worksWhileLocked:true});
yes(chooseRoute({kind:'desktop',session:locked,agent:{...c,elevated:true},requiresAdmin:true}),{route:'waiting_for_interactive_session',ready:false});
yes(chooseRoute({kind:'desktop',session:unlocked,agent:{...c,elevated:true},requiresAdmin:true}),{route:'windows.uia_guarded',ready:true});
yes(chooseRoute({kind:'irrelevant',session:unlocked,agent:c}),{route:'invalid',ready:false});
console.log('PASS_R5_LOCKED_BACKGROUND_AND_UAC_CAPABILITY_ROUTING scenarios='+checked+' secure_desktop_not_bypassed=true');
