'use strict';
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const {CONSENT_TEXT,CONTEXT,hasValidConsent,targetPrNumber,AGREEMENT_SHA256}=require('../.github/scripts/cla-gate.cjs');
const contributor={id:8001,type:'User',login:'external-test'};
const other={id:8002,type:'User',login:'unrelated'};
const timestamp='2026-09-22T12:47:33Z';
const comments=[{user:contributor,body:CONSENT_TEXT,created_at:timestamp}];
assert.equal(hasValidConsent([],contributor),false);
assert.equal(hasValidConsent(comments,contributor),true);
assert.equal(hasValidConsent(comments,other),false);
assert.equal(hasValidConsent([{user:other,body:CONSENT_TEXT,created_at:timestamp}],contributor),false);
assert.equal(hasValidConsent([{user:contributor,body:'I agree',created_at:timestamp}],contributor),false);
assert.equal(hasValidConsent([{user:contributor,body:CONSENT_TEXT+' extra',created_at:timestamp}],contributor),false);
assert.equal(hasValidConsent([{user:contributor,body:CONSENT_TEXT,created_at:'2026-09-22T11:00:00Z'}],contributor),false);
assert.equal(hasValidConsent([{user:contributor,body:CONSENT_TEXT,created_at:'not-date'}],contributor),false);
assert.equal(hasValidConsent(comments,{id:8001,type:'Bot'}),false);
assert.equal(targetPrNumber('pull_request_target',{pull_request:{number:12}}),12);
assert.equal(targetPrNumber('issue_comment',{issue:{number:31,pull_request:{url:'https://api.github.com/...'}}}),31);
assert.equal(targetPrNumber('issue_comment',{issue:{number:31}}),null);
assert.equal(CONTEXT,'YourHand CLA v1.1 / contributor consent');
assert.ok(CONSENT_TEXT.includes('proprietary')===false);
assert.ok(CONSENT_TEXT.includes(AGREEMENT_SHA256));
assert.equal(AGREEMENT_SHA256.length,64);
console.log('PASS_CLA_CONSENT_CHECKS cases=14 unsigned_fail_closed=true exact_author_and_text=true pinned_version=true');
