'use strict';
const assert=require('node:assert/strict');
const {chooseDesktopRoute,canEscalate}=require('../src/execution/router');
const selector={name:'Confirm',controlType:'Button'};
const expect={selector:{name:'Done',controlType:'Text'},property:'name',equals:'Done'};
const frame={width:360,height:200,snapshot:{controls:[{name:'Confirm',controlType:'Button',enabled:true}]}};
const choose=v=>chooseDesktopRoute({frame,...v});
assert.equal(choose({selector,expect,x:10,y:10}).mode,'semantic');
assert.equal(choose({selector,expect,x:10,y:10}).steps[0].op,'invoke');
assert.equal(choose({selector,x:10,y:10}).ok,false,'Missing postcondition must not silently choose pixel');
assert.equal(choose({selector,x:10,y:10,allowPixelFallback:true}).mode,'preview');
assert.equal(choose({selector,expect,x:360,y:0,allowPixelFallback:true}).mode,'semantic');
assert.equal(choose({selector:{name:'No Match'},expect,x:360,y:0,allowPixelFallback:true}).ok,false);
assert.equal(chooseDesktopRoute({frame:null,x:10,y:10}).code,'STALE_REFERENCE');
assert.equal(choose({x:10,y:10}).mode,'preview');
assert.equal(choose({x:360,y:10}).code,'TARGET_REQUIRED');
assert.equal(choose({selector:{name:'Confirm'},expect}).mode,'semantic');
const duplicate={...frame,snapshot:{controls:[...frame.snapshot.controls,...frame.snapshot.controls]}};
assert.equal(chooseDesktopRoute({frame:duplicate,selector,expect}).code,'AMBIGUOUS_SELECTOR');
assert.equal(chooseDesktopRoute({frame:duplicate,selector,expect,x:10,y:10,allowPixelFallback:true}).mode,'preview');
assert.equal(canEscalate({effect:'unverifiable'}),false);
assert.equal(canEscalate({effect:'confirmed'}),false);
assert.equal(canEscalate({effect:'rejected',sideEffectDispatched:true}),false);
assert.equal(canEscalate({effect:'rejected'}),true);
assert.equal(canEscalate({effect:'stale_reference'}),true);
console.log('EXECUTION_ROUTER_TESTS_OK cases=16');